name: Java CI/CD with Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v2

    # Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    # Install Chrome browser
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # Install Firefox browser
    - name: Install Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox

    # Install Microsoft Edge browser
    - name: Install Microsoft Edge
      run: |
        sudo apt-get install -y software-properties-common apt-transport-https wget
        wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable

    # Build with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Run tests with Maven
    - name: Run tests
      run: mvn test
